version: '3.8'

services:

  db:
    image: keinos/sqlite3:latest
    volumes:
      - db_value:/var/lib/Sqllite/data/

  web:
    build: ../shelter/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  db_value:
  static_value:
  media_value: